const ManagePasswordsActionsConstants = {
    GET_MANAGE_PASSWORDS_STATE: "GET_MANAGE_PASSWORDS_STATE",
    GET_MANAGE_PASSWORDS_STATE_SUCCESS: "GET_MANAGE_PASSWORDS_STATE_SUCCESS",
    GET_MANAGE_PASSWORDS_STATE_FAILURE: "GET_MANAGE_PASSWORDS_STATE_FAILURE",

    SET_MANAGE_PASSWORDS_STATE: "SET_MANAGE_PASSWORDS_STATE",
    SET_MANAGE_PASSWORDS_STATE_SUCCESS: "SET_MANAGE_PASSWORDS_STATE_SUCCESS",
    SET_MANAGE_PASSWORDS_STATE_FAILURE: "SET_MANAGE_PASSWORDS_STATE_FAILURE",

    GET_MANAGE_PASSWORDS_USER_STATE_SUCCESS: "GET_MANAGE_PASSWORDS_USER_STATE_SUCCESS",
    GET_MANAGE_PASSWORDS_USER_STATE_FAILURE: "GET_MANAGE_PASSWORDS_USER_STATE_FAILURE",

    OPEN_PASSWORDS_LIST_TAB: "OPEN_PASSWORDS_LIST_TAB"
};

export { ManagePasswordsActionsConstants };
