const LoginActionsConstants = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
  IS_USER_LOGGED_IN_SUCCESS: "IS_USER_LOGGED_IN_SUCCESS",
  IS_USER_LOGGED_IN_FAILURE: "IS_USER_LOGGED_IN_FAILURE"
};

export { LoginActionsConstants };
