const UserActionsConstants = {
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
    IS_USER_LOGGED_IN_RES: "IS_USER_LOGGED_IN_RES"
};

export { UserActionsConstants };
