const PasswordListActionsConstants = {
    UPDATE_PASSWORD: "UPDATE_PASSWORD",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",

    GET_CREDENTIALS: "GET_PASSWORD",
    GET_CREDENTIALS_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    GET_CREDENTIALS_FAILURE: "UPDATE_PASSWORD_FAILURE",

    ASK_FOR_PASSWORD_UPDATE: "ASK_FOR_PASSWORD_UPDATE",
    ASK_FOR_PASSWORD_UPDATE_ACCEPT: "ASK_FOR_PASSWORD_UPDATE_ACCEPT",
    ASK_FOR_PASSWORD_UPDATE_REJECT: "ASK_FOR_PASSWORD_UPDATE_REJECT",

    ASK_FOR_PASSWORD_SAVE: "ASK_FOR_PASSWORD_SAVE",
    ASK_FOR_PASSWORD_SAVE_ACCEPT: "ASK_FOR_PASSWORD_SAVE_ACCEPT",
    ASK_FOR_PASSWORD_SAVE_REJECT: "ASK_FOR_PASSWORD_SAVE_REJECT"
};

export { PasswordListActionsConstants };
