const PasswordListActionsConstants = {
    UPDATE_PASSWORD: "UPDATE_PASSWORD",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",

    GET_CREDENTIALS: "GET_PASSWORD",
    GET_CREDENTIALS_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    GET_CREDENTIALS_FAILURE: "UPDATE_PASSWORD_FAILURE",
};

export { PasswordListActionsConstants };
