const NotificationActionsConstants = {
    UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
    UPDATE_NOTIFICATION_SUCCESS: "UPDATE_NOTIFICATION_SUCCESS",
    UPDATE_NOTIFICATION_FAILURE: "UPDATE_NOTIFICATION_FAILURE",
};

export { NotificationActionsConstants };
