const SecurityActionsConstants = {
    UPDATE_USER_SECURITY: 'UPDATE_USER_SECURITY',
    UPDATE_USER_SECURITY_SUCCESS: "UPDATE_USER_SECURITY_SUCCESS",
    UPDATE_USER_SECURITY_FAILURE: "UPDATE_USER_SECURITY_FAILURE",

    GET_QR_CODE: 'GET_QR_CODE',
    GET_QR_CODE_SUCCESS: 'GET_QR_CODE_SUCCESS',
    GET_QR_CODE_FAILURE: 'GET_QR_CODE_FAILURE',

    VALIDATE_PIN: 'VALIDATE_PIN',
    VALIDATE_PIN_SUCCESS: 'VALIDATE_PIN_SUCCESS',
    VALIDATE_PIN_FAILURE: 'VALIDATE_PIN_FAILURE',

    VALIDATE_PIN_SERVER: 'VALIDATE_PIN_SERVER',
    VALIDATE_PIN_SERVER_SUCCESS: 'VALIDATE_PIN_SERVER_SUCCESS',
    VALIDATE_PIN_SERVER_FAILURE: 'VALIDATE_PIN_SERVER_FAILURE',
};
export { SecurityActionsConstants };
