const SecurityActionsConstants = {
    UPDATE_USER_SECURITY_SUCCESS: "UPDATE_USER_SECURITY_SUCCESS",
    UPDATE_USER_SECURITY_FAILURE: "UPDATE_USER_SECURITY_FAILURE",

    GET_QR_CODE: 'GET_QR_CODE',
    GET_QR_CODE_SUCCESS: 'GET_QR_CODE_SUCCESS',
    GET_QR_CODE_FAILURE: 'GET_QR_CODE_FAILURE'
};

export { SecurityActionsConstants };
